name: Build Docker Image (Release)

on:
  push:
    # trigger on version tag push
    tags:
      - "v*"

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  packages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Metadata: Git"
        id: git-meta
        uses: "imgg-devops/actions/git-meta@main"

      - name: "Docker: Build and Push Image"
        id: ghcr-docker
        uses: "imgg-devops/actions/ghcr-docker@main"
        with:
          version: ${{ steps.git-meta.outputs.version }}
          repository: "ekakeru/ekakeru"
          build-args: |
            SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }}

      - name: "Release: Call Dispatcher"
        id: release-dispatcher
        uses: "imgg-devops/actions/release-dispatcher@main"
        with:
          version: ${{ steps.git-meta.outputs.version }}
          use-sentry: true
          sentry-auth-token: ${{ secrets.SENTRY_AUTH_TOKEN }}
          sentry-org: ekakeru
          sentry-project: ekakeru
          sentry-environment: production
          use-ghrelease: true
          use-manifestbot: true
          manifestbot-file-path: "applications/ekakeru/deployment.yaml"
          manifestbot-key: ".spec.template.spec.containers[0].image"
          manifestbot-value: "ghcr.io/ekakeru/ekakeru:${{ steps.git-meta.outputs.version }}"
          manifestbot-token: ${{ secrets.PAT_FOR_MANIFESTBOT }}
